name: scimovement
description: A new Flutter project.

publish_to: 'none'

version: 1.17.0+35

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  collection: ^1.19.1
  http: ^1.4.0
  go_router: ^16.0.0
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.5.3
  fl_chart: ^1.0.0
  dio: ^5.8.0+1
  timezone: ^0.10.1
  intl: ^0.20.2
  push: ^3.3.3
  reactive_forms: ^18.1.1
  hexcolor: ^3.0.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0
  animated_digit: ^3.2.3
  animated_flip_counter: ^0.3.4
  hooks_riverpod: ^2.6.1
  package_info_plus: ^8.3.0
  timeago: ^3.7.1
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  timelines: ^0.1.0
  easy_image_viewer: ^1.5.1
  infinite_listview: ^1.1.0
  show_fps: ^1.0.6
  confetti: ^0.8.0
  blur: ^4.0.2
  flutter_foreground_task: ^9.1.0
  permission_handler: ^11.0.0
  flutter_blue_plus: ^1.36.6
  polar:
    path: ../../polar-flutter
    # git:
    #   url: https://github.com/mikeread-dev/polar.git
    #   ref: master
      # url: https://github.com/hci-gu/polar.git
      # ref: master
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/licenses/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800